badges added (v.0.17.0)
pozabil/test_guru pull request #17
Opened 2022-02-19 19:30 UTC by pozabil

Разработал функционал который позволит пользователям получать бэйджи (награды) за успешное прохождение тестов.

Бэйджи представляются моделью Badge
Пользователь может получать один и тот же бэйдж более одного раза
Бэйдж обязательно содержит атрибуты:
    Название
    Имя файла с изображением (Делать загрузку изображений не нужно. Это может быть статический файл с изображением который вручную добавляется в проект. Либо это может быть любой URL с изображением бэйджа)
Выдача бэйджов происходит автоматически после завершения теста
Управление бэйджами осуществляется администратором
При создании бэйджа администратор также назначает правило которое определяет порядок выдачи бэйджа. Примеры правил:
    Выдать бэйдж после успешного прохождения всех тестов из категории Backend
    Выдать бэйдж после успешного прохождения теста с первой попытки
    Выдать бэйдж после успешного прохождения всех тестов определённого уровня
Допускается что критерии правил заданы заранее, например на уровне атрибутов модели
Пользователь в любой момент времени может посмотреть список всех существующих и заработанных бэйджей

2022-02-20 18:11 UTC, BubuntuClu requested changes

2022-02-20 18:11 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    current_user.tests.push(@test) unless current_user.has_active_test?(@test)
эта проверка будет мешать пользователю. вдруг он захочет другой тест проходить, а ты лишаешь его этой возможности

2022-02-20 18:11 UTC, BubuntuClu commented on app/javascript/utilities/rule_selector.js
> +	if (ruleType == 'success_by_category') {
очень плохое решение. при добавлении полей, код будет разрастаться. почему бы просто не сделать селект с выбором правил из списка?

2022-02-20 18:11 UTC, BubuntuClu commented on app/models/badge.rb
> +  validates :rule_condition, format: { with: NATURAL_NUMBER_FORMAT }, if: :rule_condition_is_level?
мне кажется, это лишняя валидация

2022-02-20 18:11 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  before_update :before_update_next_question, :before_update_set_success
не стоит перечислять несколько методов в одном колбэке.
и лучше вообще не колбэком реализовать выставление успеха, а напрямую вызвать метод где-нибудь в логике приложения

2022-02-20 18:11 UTC, BubuntuClu commented on app/models/user.rb
> +  def what_try?(test)
метод отдает значение в непривычно формате. ожидается что метод с `?` в имени вернет `true/false`

2022-02-20 18:11 UTC, BubuntuClu commented on app/models/user_badge.rb
> +      case badge.rule
нужно переделать этот код. при добавлении правил, будет расти этот код. нужно сделать оптимальней вызов методов проверки

2022-02-20 18:11 UTC, BubuntuClu commented on app/models/user_badge.rb
> +        current_user.badges.push(badge) if (test_passage.success? && current_user.what_try?(current_test) == 1 )
` current_user.badges.push(badge)` дублирование кода в каждой ветке, надо отрефакторить

2022-02-20 18:11 UTC, BubuntuClu commented on app/models/user_badge.rb
> +  def self.check(test_passage)
проверкой должен заниматься какой-ниудь сервис, но не модель. всю логику выдачи баджей надо вынести в сервис

2022-02-20 18:11 UTC, BubuntuClu commented on app/models/user_badge.rb
> +        filtered_tests = Test.filter_by_category(badge.rule_condition)
получение данных надо свести к двум запросам в БД. тесты по категории/уровню, тесты котоыре прошел пользователь и сравнить два массива. без рубишных обработок массивов

2022-02-20 18:36 UTC, pozabil commented on app/controllers/admin/badges_controller.rb
> +    @badge = current_user.created_badges.new(badge_params)
Это создание бейджа администратором, а не получение бейджа пользователем.

2022-02-20 18:36 UTC, pozabil commented on app/controllers/tests_controller.rb
> +    current_user.tests.push(@test) unless current_user.has_active_test?(@test)
Это не мешает пользователю проходить тесты, это позволяет пользователю продолжить тест, если он его уже начал, но не закончил. На другие тесты помимо начатого это не влияет.

2022-02-20 18:42 UTC, pozabil commented on app/javascript/utilities/rule_selector.js
> +	if (ruleType == 'success_by_category') {
Там и есть селектор с выбором правил, этот js код делает так, чтобы в случае выбора определенного типа получения бейджа, можно было бы выбирать дополнительные условия. (При выборе получение бейджа за категорию, чтобы появлялся селектор с категориями, при получении бейджа за уровень, появлялся филд с вводом уровня)
![125_1](https://user-images.githubusercontent.com/87725612/154858637-a35fba2c-0a7d-4856-a787-6b42c346dbed.png)
![125_2](https://user-images.githubusercontent.com/87725612/154858641-bbd7aec0-9cb5-4b4c-8637-2ddb2b7e5b4e.png)
![125_3](https://user-images.githubusercontent.com/87725612/154858642-c019cdd0-de7a-4010-a8a6-222e86370739.png)

2022-02-20 18:42 UTC, pozabil commented on app/models/badge.rb
> +  validates :rule_condition, format: { with: NATURAL_NUMBER_FORMAT }, if: :rule_condition_is_level?
если не сделать, то при выборе типа правила получения бейджа за прохождение определенного уровня в условия получения можно будет записать не только значения уровня => будет выдавать ошибку и невалидно.

2022-02-20 18:43 UTC, pozabil commented on app/models/test_passage.rb
> +  before_update :before_update_next_question, :before_update_set_success
А почему коллбеком плохой вариант?

2022-02-20 18:44 UTC, pozabil commented on app/models/user.rb
> +  def what_try?(test)
Понял, исправлю.

2022-02-20 18:45 UTC, pozabil commented on app/models/user_badge.rb
> +  def self.check(test_passage)
Окей, но почему? Через модель нелогичное решение?

2022-05-21 18:12 UTC, BubuntuClu requested changes

2022-05-21 18:12 UTC, BubuntuClu commented on app/services/user_badges_update_service.rb
> +      @current_user.badges.push(badge) if (@test_passage.success? && send("#{badge.rule}_badge_check_success", badge))
зачем тут делать проверку на успешное прохождение теста, если можно сделать проверку уровнем выше и не вызывать сервис в принципе если тест не пройден успешно?
сейчас ты будешь тратить ресурсы машины на запросы в БД, чтобы получить ассоциации теста/пользователя, все баджи и по итогу узнать что это все лишнее, так как тест не пройден успешно

2022-05-21 18:12 UTC, BubuntuClu commented on app/models/user.rb
> +    test_passages.where(test_id: test.id).size == 1 ? true : false
`test_passages.where(test_id: test.id).size == 1` самое это сравнение и возвращает `true/false`, не надо самому писать обработку поверх этого

2022-05-21 18:12 UTC, BubuntuClu commented on app/models/user.rb
> +    test_passages.where(test_id: test.id).size == 1 ? true : false
и не думаю что этот метод должен быть тут. как прохождение теста с первой попытки, относится к модели пользователя?
мне кжается, стоит оставить этот метод в самом сервисе выдачи баджей

2022-05-21 18:12 UTC, BubuntuClu commented on app/services/user_badges_update_service.rb
> +    if @test_passage.test.category.title == badge.rule_condition
```
return false if if @test_passage.test.category.title != badge.rule_condition

filtered_tests = Test.filter_by_category(badge.rule_condition)
....
```
лучше так писать, чтобы не было огромного вложенного куска кода

2022-05-21 18:12 UTC, BubuntuClu commented on app/services/user_badges_update_service.rb
> +  def filtered_tests_complete_succesfully?(filtered_tests)
ой ой ой, это что тут за искусственный интелект построенный на if`ах?)
нужно все решить максимально через БД.
по идеи у тебя будет два запроса к базе на проверку тестов категории/уровня. 1 - найти все тесты которые надо пройти. 2 - найти все тесты которые прошел из этого. дальше только сравнить два массива.

никаких циклов и кучи проверок через if не должно быть

2022-05-25 10:53 UTC, merged